src/django_project/urls.py
from django.contrib import admin
from django.urls import path

from apps.sleepcontrolapp.views import (
    get_events,
    add_event,
    delete_event,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("get/", get_events, name="main"),
    path("add/", add_event, name="add"),
    path("delete/", delete_event, name="delete"),
]

src/apps/sleepcontrolapp/models.py
from django.db import models


class SleepPoint(models.Model):
    class EventType(models.TextChoices):
        UP = "UP", "Подьем"
        DOWN = "DOWN", "Отбой"

    event = models.CharField(
        max_length=4, verbose_name="Событие", choices=EventType.choices
    )
    date = models.DateField(verbose_name="Дата")
    time = models.TimeField(verbose_name="Время")

    class Meta:
        verbose_name = "Точка сна"
        verbose_name_plural = "Точки сна"

src/apps/sleepcontrolapp/forms.py
from django.forms import ModelForm

from apps.sleepcontrolapp.models import SleepPoint


class SleepForms(ModelForm):
    class Meta:
        model = SleepPoint
        fields = ["event", "date", "time"]

src/apps/sleepcontrolapp/views.py
from apps.sleepcontrolapp import service
from django.http import HttpResponseBadRequest
from django.shortcuts import render, redirect

from apps.sleepcontrolapp.forms import SleepForms


def get_events(request):
    events = service.get_events()
    return render(
        request,
        "sleepcontrolapp/get_table.html",
        {"events": events},
    )


def add_event(request):
    form = SleepForms()
    if request.method == "POST":
        form = SleepForms(request.POST)
        if form.is_valid():
            if service.event_exists(**form.cleaned_data):
                return HttpResponseBadRequest("Запись уже существует")
            service.create_event(**form.cleaned_data)
            return redirect("main")
    return render(
        request, "sleepcontrolapp/form_for_data.html", {"form": form}
    )


def delete_event(request):
    service.delete_event(pk=int(request.POST["pk"]))
    return redirect("main")

src/templates/sleepcontrolapp/form_for_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action='/add/' method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
</body>
</html>

src/templates/sleepcontrolapp/get_table.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    
    <table cellspacing="20px">
        {% for data in events%}
        <form action="/delete/" method="post">
            {% csrf_token %}
            <tr><td>{{ data.get_event_display }}</td>
                <td>{{ data.date|date:'Y-m-d' }}</td>
                <td>{{ data.time|time:'H:i' }}</td>
                <td><input type="hidden" value="{{ data.pk }}" name="pk"></td>
                <td><input type="submit" value="Удалить"></td>
            </tr>
        </form>
        {% endfor %}
    </table>
    <a href="/add" style="padding-left: 150px">Добавить</a>
</body>
</html>